name: AmongUs
version: 1.0
description: Among Us in MC
api-version: 1.16
main: com.taahyt.amongus.AmongUs
authors: [Taah, DeJayDev]
commands:
  join:
    description: "Yes"
  tasks:
    description: "Yes"